# Generated by Django 5.0.3 on 2024-05-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VendorProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='VendorProfile.vendorprofile')),
                ('date', models.DateField(auto_now_add=True)),
                ('on_time_delivery_rate', models.FloatField(default=0)),
                ('quality_rating_avg', models.FloatField(default=0)),
                ('avg_response_time', models.DurationField(default=None, null=True)),
                ('fulfilment_rate', models.FloatField(default=0)),
            ],
        ),
    ]
