# Generated by Django 5.0.3 on 2024-05-01 15:17

import Orders.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VendorProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('po_number', models.BigAutoField(default=Orders.models.generate_random_po_number, primary_key=True, serialize=False)),
                ('order_status', models.CharField(default='Pending', max_length=20)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 15, 17, 16, 310437, tzinfo=datetime.timezone.utc))),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2024, 5, 2, 20, 47, 16, 310437))),
                ('items', models.JSONField(default={'Product_Name': 'Quantity'})),
                ('quantity', models.IntegerField(default=0)),
                ('quality_rating', models.FloatField(default=0)),
                ('issue_date', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 15, 17, 16, 310437, tzinfo=datetime.timezone.utc))),
                ('acknowledgement_date', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 15, 17, 16, 310437, tzinfo=datetime.timezone.utc))),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorProfile.vendorprofile')),
            ],
        ),
    ]
